# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest


variables:
  buildConfiguration: 'Release'
  serviceConnection : 'az-serviceprincipal'
  resourceGroupName: 'RapidAutoMVC20220630100135ResourceGroup'
  location: 'canadacentral'
  templateFile: '**/main.bicep'
  webAppName: 'TP2'
    


steps:
- task: AzureCLI@2
  displayName: Preview Bicep Changes
  inputs:    
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az --version     
      az deployment group what-if --resource-group $(resourceGroupName) \
         --template-file $(templateFile) \
         --parameters webAppName=$(webAppName)

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration$(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/*.api*.csproj'
 
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
  displayName: 'Génération du package de publication'      