// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RapidAuto.Commandes.API.Data;

#nullable disable

namespace RapidAuto.Commandes.API.Migrations
{
    [DbContext(typeof(CommandeDbContext))]
    [Migration("20220407173433_MigrationInitiale")]
    partial class MigrationInitiale
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("RapidAuto.Commandes.API.Models.Commande", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("UtilisateurID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VehiculeID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Utilisateurs");
                });
#pragma warning restore 612, 618
        }
    }
}
